export { default as DashboardLayout } from './DashboardLayout'
export { default as NhanDienMRI } from './NhanDienMRI'
export { default as History } from './History'
export { default as DetailHistory } from './DetailHistory'
export { default as Error } from './Error'
export { default as HomeLayout } from './HomeLayout'
export { default as Landing } from './Landing'
export { default as Login } from './Login'
export { default as Profile } from './Profile'
export { default as Register } from './Register'

